# Generated by Django 5.1 on 2024-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourservice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('b', models.CharField(max_length=555)),
                ('h4', models.CharField(max_length=999)),
                ('p', models.CharField(max_length=999)),
            ],
        ),
    ]
