# Generated by Django 5.1 on 2024-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=999)),
                ('h4', models.CharField(max_length=355)),
                ('p', models.CharField(max_length=777)),
                ('h5b', models.CharField(max_length=255)),
            ],
        ),
    ]
