# Generated by Django 5.1 on 2024-09-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='h5',
            field=models.CharField(null=True),
        ),
    ]
