# Generated by Django 5.1 on 2024-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('subject', models.CharField(max_length=999)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=999)),
            ],
        ),
    ]
